package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Climerio Neto
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        mnequipamento = new javax.swing.JMenu();
        mnEquipamentoTodos = new javax.swing.JMenuItem();
        mnEquipamentoDisponiveis = new javax.swing.JMenuItem();
        mnEquipamentoLocados = new javax.swing.JMenuItem();
        mnEquipamentoDefeito = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface");

        jButton1.setText("Cliente");

        jButton2.setText("Equipamentos");

        mnequipamento.setText("Equipamentos");

        mnEquipamentoTodos.setText("Todos");
        mnEquipamentoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEquipamentoTodosActionPerformed(evt);
            }
        });
        mnequipamento.add(mnEquipamentoTodos);

        mnEquipamentoDisponiveis.setText("Disponiveis");
        mnEquipamentoDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEquipamentoDisponiveisActionPerformed(evt);
            }
        });
        mnequipamento.add(mnEquipamentoDisponiveis);

        mnEquipamentoLocados.setText("Locados");
        mnequipamento.add(mnEquipamentoLocados);

        mnEquipamentoDefeito.setText("Com Defeito");
        mnequipamento.add(mnEquipamentoDefeito);

        MenuBar.add(mnequipamento);

        menuClientes.setText("Clientes");

        jMenuItem6.setText("Todos");
        menuClientes.add(jMenuItem6);

        jMenuItem5.setText("Debitos");
        menuClientes.add(jMenuItem5);

        MenuBar.add(menuClientes);

        menuRelatorios.setText("Relatorios");

        jMenu6.setText("Equipamentos ");

        jMenuItem8.setText("Locados");
        jMenu6.add(jMenuItem8);

        jMenuItem11.setText("Devolvidos");
        jMenu6.add(jMenuItem11);

        jMenuItem9.setText("Defeitos");
        jMenu6.add(jMenuItem9);

        menuRelatorios.add(jMenu6);

        jMenu7.setText("Clientes");

        jMenuItem7.setText("Todos");
        jMenu7.add(jMenuItem7);

        jMenuItem10.setText("Debitos");
        jMenu7.add(jMenuItem10);

        menuRelatorios.add(jMenu7);

        MenuBar.add(menuRelatorios);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 291, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnEquipamentoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEquipamentoTodosActionPerformed
        
        Cadastro cad = new Cadastro("todos");
        cad.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_mnEquipamentoTodosActionPerformed

    private void mnEquipamentoDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEquipamentoDisponiveisActionPerformed
        
        Cadastro cad = new Cadastro("disponiveis");
        cad.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_mnEquipamentoDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem mnEquipamentoDefeito;
    private javax.swing.JMenuItem mnEquipamentoDisponiveis;
    private javax.swing.JMenuItem mnEquipamentoLocados;
    private javax.swing.JMenuItem mnEquipamentoTodos;
    private javax.swing.JMenu mnequipamento;
    // End of variables declaration//GEN-END:variables
}
