/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kelli
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem11 = new javax.swing.JMenuItem();
        MainPNL = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        mnCadastrarEquipamento = new javax.swing.JMenuItem();
        mnCadastrarLocacao = new javax.swing.JMenuItem();
        mnCadastrarReserva = new javax.swing.JMenuItem();
        mnExibir = new javax.swing.JMenu();
        mnExibirEquipamento = new javax.swing.JMenuItem();
        mnExibirReservas = new javax.swing.JMenuItem();
        mnExibirLocacao = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mnRelatorioEquipamento = new javax.swing.JMenuItem();
        mnRelatorioReserva = new javax.swing.JMenuItem();
        mnRelatorioLocacao = new javax.swing.JMenuItem();
        mnAdmin = new javax.swing.JMenu();
        mnAdminFunc = new javax.swing.JMenu();
        mnAdminFuncCad = new javax.swing.JMenuItem();
        mnAdminFuncExib = new javax.swing.JMenuItem();

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MainPNLLayout = new javax.swing.GroupLayout(MainPNL);
        MainPNL.setLayout(MainPNLLayout);
        MainPNLLayout.setHorizontalGroup(
            MainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        MainPNLLayout.setVerticalGroup(
            MainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        mnCadastrar.setText("Cadastrar");

        mnCadastrarEquipamento.setText("Equipamento");
        mnCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarEquipamentoActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadastrarEquipamento);

        mnCadastrarLocacao.setText("Registrar locação");
        mnCadastrarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarLocacaoActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadastrarLocacao);

        mnCadastrarReserva.setText("Registrar Reserva");
        mnCadastrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarReservaActionPerformed(evt);
            }
        });
        mnCadastrar.add(mnCadastrarReserva);

        jMenuBar1.add(mnCadastrar);

        mnExibir.setText("Exibir");

        mnExibirEquipamento.setText("Equipamentos");
        mnExibirEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExibirEquipamentoActionPerformed(evt);
            }
        });
        mnExibir.add(mnExibirEquipamento);

        mnExibirReservas.setText("Reservas");
        mnExibirReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExibirReservasActionPerformed(evt);
            }
        });
        mnExibir.add(mnExibirReservas);

        mnExibirLocacao.setText("Locações");
        mnExibirLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExibirLocacaoActionPerformed(evt);
            }
        });
        mnExibir.add(mnExibirLocacao);

        jMenuBar1.add(mnExibir);

        mnRelatorio.setText("Relatórios");

        mnRelatorioEquipamento.setText("Equipamentos");
        mnRelatorioEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioEquipamentoActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnRelatorioEquipamento);

        mnRelatorioReserva.setText("Reservas");
        mnRelatorioReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioReservaActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnRelatorioReserva);

        mnRelatorioLocacao.setText("Locações");
        mnRelatorioLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioLocacaoActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnRelatorioLocacao);

        jMenuBar1.add(mnRelatorio);

        mnAdmin.setText("ADMIN");

        mnAdminFunc.setText("Funcionarios");

        mnAdminFuncCad.setText("Cadastrar");
        mnAdminFuncCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminFuncCadActionPerformed(evt);
            }
        });
        mnAdminFunc.add(mnAdminFuncCad);

        mnAdminFuncExib.setText("Exibir");
        mnAdminFuncExib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminFuncExibActionPerformed(evt);
            }
        });
        mnAdminFunc.add(mnAdminFuncExib);

        mnAdmin.add(mnAdminFunc);

        jMenuBar1.add(mnAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExibirEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExibirEquipamentoActionPerformed

        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new SrcEquip(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new SrcEquip(true));

        MainPNL.updateUI();

    }//GEN-LAST:event_mnExibirEquipamentoActionPerformed

    private void mnCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarEquipamentoActionPerformed

        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new CadEquip(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new CadEquip());

        MainPNL.updateUI();
    }//GEN-LAST:event_mnCadastrarEquipamentoActionPerformed

    private void mnCadastrarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarLocacaoActionPerformed

        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new RegLocacao(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new CadPessoa());

        MainPNL.updateUI();

    }//GEN-LAST:event_mnCadastrarLocacaoActionPerformed

    private void mnCadastrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarReservaActionPerformed
        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new RegReserva(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new RegReserva());

        MainPNL.updateUI();
    }//GEN-LAST:event_mnCadastrarReservaActionPerformed

    private void mnExibirLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExibirLocacaoActionPerformed

        BorderLayout bl = new BorderLayout();

        try {
            bl.addLayoutComponent(new SrcLocacao(), null);
            MainPNL.setLayout(bl);
            MainPNL.removeAll();
            MainPNL.add(new SrcLocacao());

            MainPNL.updateUI();

        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_mnExibirLocacaoActionPerformed

    private void mnExibirReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExibirReservasActionPerformed

        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new SrcReserva(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new SrcReserva());

        MainPNL.updateUI();

    }//GEN-LAST:event_mnExibirReservasActionPerformed

    private void mnAdminFuncCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminFuncCadActionPerformed

        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new CadPessoa(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new CadPessoa());

        MainPNL.updateUI();

    }//GEN-LAST:event_mnAdminFuncCadActionPerformed

    private void mnAdminFuncExibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminFuncExibActionPerformed
        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new SrcPessoa(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new SrcPessoa());

        MainPNL.updateUI();
    }//GEN-LAST:event_mnAdminFuncExibActionPerformed

    private void mnRelatorioEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioEquipamentoActionPerformed
        
        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new RelEquip(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new RelEquip());

        MainPNL.updateUI();
        
    }//GEN-LAST:event_mnRelatorioEquipamentoActionPerformed

    private void mnRelatorioReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioReservaActionPerformed
        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new RelReserva(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new RelReserva());

        MainPNL.updateUI();
        
    }//GEN-LAST:event_mnRelatorioReservaActionPerformed

    private void mnRelatorioLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioLocacaoActionPerformed
        BorderLayout bl = new BorderLayout();

        bl.addLayoutComponent(new RelLocacao(), null);

        MainPNL.setLayout(bl);
        MainPNL.removeAll();
        MainPNL.add(new RelLocacao());

        MainPNL.updateUI();
        
    }//GEN-LAST:event_mnRelatorioLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel MainPNL;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenu mnAdmin;
    private javax.swing.JMenu mnAdminFunc;
    private javax.swing.JMenuItem mnAdminFuncCad;
    private javax.swing.JMenuItem mnAdminFuncExib;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenuItem mnCadastrarEquipamento;
    private javax.swing.JMenuItem mnCadastrarLocacao;
    private javax.swing.JMenuItem mnCadastrarReserva;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JMenuItem mnExibirEquipamento;
    private javax.swing.JMenuItem mnExibirLocacao;
    private javax.swing.JMenuItem mnExibirReservas;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuItem mnRelatorioEquipamento;
    private javax.swing.JMenuItem mnRelatorioLocacao;
    private javax.swing.JMenuItem mnRelatorioReserva;
    // End of variables declaration//GEN-END:variables
}
